// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

export const environment = {
  production: false,
  // url: "http://localhost:7000/api/",
  // loginUrl: "/iNCRediCabs/login",
  // logoutUrl: "/iNCRediCabs/logout",
  // checkLoginUrl: "/iNCRediCabs/check-login-status",
  // addEmployeeUrl: "/iNCRediCabs/add-employee",
  // activateEmployeeUrl: "/iNCRediCabs/activate-employee",
  // deactivateEmployeeUrl: "/iNCRediCabs/deactivate-employee",
  // editEmployeeUrl: "/iNCRediCabs/edit-employee",
  // viewEmployeeUrl: "/iNCRediCabs/view-employee",
  // getManagerByNameUrl: "/iNCRediCabs/get-manager-by-name",
  // getAllManagersUrl: "/iNCRediCabs/get-all-managers",
  // getAllRolesUrl: "/iNCRediCabs/get-all-roles",
  // newAccSetupQlidUrl: "/iNCRediCabs/new-acc-setup",
  // forgotpasswordUrl:  "/iNCRediCabs/forgot-password",
  // forgotpassSetPasswordUrl:  "/iNCRediCabs/forgot-password/set-password",
  // accSetupSetPasswordUrl: "/iNCRediCabs/new-acc-setup/set-password",
  // verifyPwdTokenUrl: "/iNCRediCabs/verify-pwd-token",
  
  url: "http://localhost:8080/NCAB",
  loginUrl:                   this.url + "/EmployeeService/login",
  logoutUrl:                  this.url + "/EmployeeService/logout",
  checkLoginUrl:              this.url + "/EmployeeService/check-login-status",
  addEmployeeUrl:             this.url + "/EmployeeService/add-employee",
  activateEmployeeUrl:        this.url + "/EmployeeService/activate-employee",
  deactivateEmployeeUrl:      this.url + "/EmployeeService/deactivate-employee",
  editEmployeeUrl:            this.url + "/EmployeeService/edit-employee",
  viewEmployeeUrl:            this.url + "/EmployeeService/view-employee",
  getManagerByNameUrl:        this.url + "/EmployeeService/get-manager-by-name",
  getAllManagersUrl:          this.url + "/EmployeeService/get-all-managers",
  getAllRolesUrl:             this.url + "/EmployeeService/get-all-roles",
  newAccSetupQlidUrl:         this.url + "/EmployeeService/new-acc-setup",
  forgotpasswordUrl:          this.url + "/EmployeeService/forgot-password",
  forgotpassSetPasswordUrl:   this.url + "/EmployeeService/forgot-password/set-password",
  accSetupSetPasswordUrl:     this.url + "/EmployeeService/new-acc-setup/set-password",
  verifyPwdTokenUrl:          this.url + "/EmployeeService/verify-pwd-token",
  getrequestUrl:              this.url + "/RequestService/getrequest",
  allocateRequest:            this.url + "/RequestService/onApproved",
  employeeRequest:            this.url + "/ReportService/employeereport",
  managerUrl:                 this.url + "/ReportService/managerreport",
  vendorUrl:                  this.url + "/ReportService/vendorreport",
};